export const EMPREENDIMENTOS: string[] = [
  "Não informado",
  "Alphaville Nova Esplanada 1 e 2",
  "Alphaville Nova Esplanada 3 e 4",
  "Alphaville São Camilo",
  "Altavis Aldeia",
  "Alvorá Nova Iguaçu",
  "Alvorá Parauapebas",
  "Alvorá Villágio",
  "Aruã Brisas",
  "Aruã Brisas 2",
  "Bella Cittá",
  "Bosque do Horto",
  "Carmela",
  "Central Parque e Salto Comercial",
  "Doca Vetorasso",
  "Jardim Alvorada Araraquara",
  "LUAR COMERCIAL DO OESTE",
  "LUAR DA BARRA",
  "LUAR DAS PALMEIRAS",
  "LUAR DE ALDEIA",
  "LUAR DE ARAPIRACA",
  "LUAR DE ARAPIRACA II",
  "LUAR DE CAJAZEIRAS",
  "LUAR DE CAMACARI",
  "LUAR DE CANAÃ",
  "LUAR DE ESTANCIA",
  "LUAR DE ITABERABA",
  "LUAR DE LAGARTO",
  "LUAR DE SANTA LUZIA",
  "LUAR DE SANTANA",
  "LUAR DE SUMARE",
  "LUAR DE VITÓRIA",
  "LUAR DO CAMPESTRE",
  "LUAR DO CARUARU",
  "LUAR DO CERRADO",
  "LUAR DO JURITY",
  "LUAR DO NORTE",
  "LUAR DO OESTE",
  "LUAR DO PRÍNCIPE",
  "LUAR VALE DO ASSU",
  "Paradis Canoas",
  "Parque Alvorada",
  "Parque Pedra Bonita",
  "Portal de Bragança",
  "Portal de Bragança Horizonte",
  "Praça do Sol",
  "Quinta do Golfe",
  "Reserva Amary",
  "Reserva Bonsucesso",
  "Reserva Central Parque",
  "Residencial Itahyê",
  "Residencial São José",
  "Terras de Santa Martha",
  "Urban Parque",
  "Urban Parque Incorporação",
  "Verana Cachoeiro",
  "Verana Macapá",
  "Verana Parque Alvorada",
  "Verana Porto Velho",
  "Verana Reserva Imperial",
  "Verana São José",
  "Verana Teresina",
  "Verana Várzea Grande",
  "Villa BelaVista",
  "Villa Dáquila",
  "Vívea Camaçari",
  "Vívea Rio Grande",
];

// Partial company name fragments for contestação/apelação client filtering
export const CLIENT_COMPANY_FRAGMENTS: string[] = [
  "cipasa",
  "nova cipasa",
  "nova colorado",
  "consórcio de urbanização",
  "consorcio de urbanizacao",
  "consórcio de desenvolvimento",
  "consorcio de desenvolvimento",
  "lote 01 empreendimentos",
  "ellensbrook",
  "marsala",
  "viel participacoes",
  "marialice empreendimento",
  "novavida",
  "aldeia ald1",
  "fazenda roseira",
  "alphaville",
  // Col* SPEs — LUAR empreendimentos (Nova Cipasa group)
  "colagarto",
  "colapiraca",
  "colaritinga",
  "colaru",
  "colassu",
  "coldeia",
  "colema",
  "colestancia",
  "colfeira",
  "colitaberaba",
  "colitama",
  "coljaz",
  "colmaçari",
  "colmacari",
  "colmeira",
  "colpat",
  "colsantana",
  "coluzia",
  "colvitória",
  "colvitoria",
  "colbarra",
];
